#!/usr/bin/env python3
"""Turn a DMA table JSON into the filelist YAML Torch resolves named offsets against.

Usage: python3 make_filelist.py dma/<version>.json assets/yml/<version>.filelist.yml

Torch reads this via `filelist:` in the rom config (Torch PR #253) and uses it to
resolve segment offsets written as DMA file names rather than hex ROM addresses:

    :config:
      segments:
        - [ 6, object_link_child ]

The offset emitted per file is its `phys_start` -- the ROM offset a segment base
points at. Entries flagged absent (phys 0xFFFFFFFF: declared in the ROM's virtual
map but carrying no data) are left out, so naming one is a hard error at
extraction time instead of a segment pointed at 0xFFFFFFFF. See docs/mm-dma.md.
"""

import json
import sys


def main():
    if len(sys.argv) != 3:
        print(__doc__.strip().splitlines()[2], file=sys.stderr)
        return 2

    dma_path, out_path = sys.argv[1], sys.argv[2]

    with open(dma_path) as f:
        dma = json.load(f)

    lines = ["# Generated by tools/make_filelist.py from " + dma_path,
             "# DMA file name -> phys_start, for Torch's `filelist:` offset lookup.",
             "Files:"]
    written = skipped = 0
    for name, entry in dma.items():
        if entry.get("absent"):
            skipped += 1
            continue
        lines.append(f"  - {name}: {entry['phys_start']}")
        written += 1

    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {written} entries to {out_path} ({skipped} absent entries omitted)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
